version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: questions
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    command: ["--bind_ip_all"]
